# Configuration for Release Drafter
# https://github.com/release-drafter/release-drafter

name-template: 'NuGet Version $RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

# Map PR labels to release-note categories (matches existing RELEASENOTES.md style)
categories:
  - title: '__Breaking Changes__'
    labels:
      - 'breaking-change'
  - title: '__Bug Fixes__'
    labels:
      - 'bug'
      - 'fix'
  - title: '__API Changes__'
    labels:
      - 'enhancement'
      - 'api-change'
      - 'Missing Feature'
  - title: '__Issues Fixed__'
    labels:
      - 'issue-fixed'

# Entries that don't match any category go under this heading
change-template: '$TITLE (#$NUMBER)<br/>'
change-title-escapes: '\<*_&'

# Exclude certain labels from appearing in release notes at all
exclude-labels:
  - 'skip-changelog'
  - 'dependencies'
  - 'documentation'
  - 'ci'

# Version resolver: bump version based on labels
version-resolver:
  major:
    labels:
      - 'breaking-change'
  minor:
    labels:
      - 'enhancement'
      - 'api-change'
      - 'Missing Feature'
  patch:
    labels:
      - 'bug'
      - 'fix'
      - 'issue-fixed'
  default: patch

# Template for the draft release body
template: |
  # NuGet Version $RESOLVED_VERSION

  $CHANGES
