// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: tensorboard/compat/proto/coordination_config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tensorboard {

  /// <summary>Holder for reflection information generated from tensorboard/compat/proto/coordination_config.proto</summary>
  public static partial class CoordinationConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for tensorboard/compat/proto/coordination_config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CoordinationConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjJ0ZW5zb3Jib2FyZC9jb21wYXQvcHJvdG8vY29vcmRpbmF0aW9uX2NvbmZp",
            "Zy5wcm90bxILdGVuc29yYm9hcmQinQIKGUNvb3JkaW5hdGlvblNlcnZpY2VD",
            "b25maWcSFAoMc2VydmljZV90eXBlGAEgASgJEhYKDnNlcnZpY2VfbGVhZGVy",
            "GAIgASgJEhsKE2VuYWJsZV9oZWFsdGhfY2hlY2sYAyABKAgSJgoeY2x1c3Rl",
            "cl9yZWdpc3Rlcl90aW1lb3V0X2luX21zGAQgASgDEh8KF2hlYXJ0YmVhdF90",
            "aW1lb3V0X2luX21zGAUgASgDEhgKEGNvb3JkaW5hdGVkX2pvYnMYBiADKAkS",
            "Jgoec2h1dGRvd25fYmFycmllcl90aW1lb3V0X2luX21zGAcgASgDEioKImFn",
            "ZW50X2Rlc3RydWN0aW9uX3dpdGhvdXRfc2h1dGRvd24YCCABKAhCV1pVZ2l0",
            "aHViLmNvbS90ZW5zb3JmbG93L3RlbnNvcmZsb3cvdGVuc29yZmxvdy9nby9j",
            "b3JlL3Byb3RvYnVmL2Zvcl9jb3JlX3Byb3Rvc19nb19wcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Tensorboard.CoordinationServiceConfig), global::Tensorboard.CoordinationServiceConfig.Parser, new[]{ "ServiceType", "ServiceLeader", "EnableHealthCheck", "ClusterRegisterTimeoutInMs", "HeartbeatTimeoutInMs", "CoordinatedJobs", "ShutdownBarrierTimeoutInMs", "AgentDestructionWithoutShutdown" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Coordination service configuration parameters.
  /// The system picks appropriate values for fields that are not set.
  /// </summary>
  public sealed partial class CoordinationServiceConfig : pb::IMessage<CoordinationServiceConfig> {
    private static readonly pb::MessageParser<CoordinationServiceConfig> _parser = new pb::MessageParser<CoordinationServiceConfig>(() => new CoordinationServiceConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CoordinationServiceConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tensorboard.CoordinationConfigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CoordinationServiceConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CoordinationServiceConfig(CoordinationServiceConfig other) : this() {
      serviceType_ = other.serviceType_;
      serviceLeader_ = other.serviceLeader_;
      enableHealthCheck_ = other.enableHealthCheck_;
      clusterRegisterTimeoutInMs_ = other.clusterRegisterTimeoutInMs_;
      heartbeatTimeoutInMs_ = other.heartbeatTimeoutInMs_;
      coordinatedJobs_ = other.coordinatedJobs_.Clone();
      shutdownBarrierTimeoutInMs_ = other.shutdownBarrierTimeoutInMs_;
      agentDestructionWithoutShutdown_ = other.agentDestructionWithoutShutdown_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CoordinationServiceConfig Clone() {
      return new CoordinationServiceConfig(this);
    }

    /// <summary>Field number for the "service_type" field.</summary>
    public const int ServiceTypeFieldNumber = 1;
    private string serviceType_ = "";
    /// <summary>
    /// Type of coordination service implementation to enable.
    /// For example, setting the service type as "standalone" starts a service
    /// instance on the leader task to provide the coordination services such as
    /// heartbeats and consistent key-value store.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ServiceType {
      get { return serviceType_; }
      set {
        serviceType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "service_leader" field.</summary>
    public const int ServiceLeaderFieldNumber = 2;
    private string serviceLeader_ = "";
    /// <summary>
    /// Address where the coordination service instance is hosted.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ServiceLeader {
      get { return serviceLeader_; }
      set {
        serviceLeader_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "enable_health_check" field.</summary>
    public const int EnableHealthCheckFieldNumber = 3;
    private bool enableHealthCheck_;
    /// <summary>
    /// Whether to enable the health check mechanism.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool EnableHealthCheck {
      get { return enableHealthCheck_; }
      set {
        enableHealthCheck_ = value;
      }
    }

    /// <summary>Field number for the "cluster_register_timeout_in_ms" field.</summary>
    public const int ClusterRegisterTimeoutInMsFieldNumber = 4;
    private long clusterRegisterTimeoutInMs_;
    /// <summary>
    /// Maximum wait time for all members in the cluster to be registered.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long ClusterRegisterTimeoutInMs {
      get { return clusterRegisterTimeoutInMs_; }
      set {
        clusterRegisterTimeoutInMs_ = value;
      }
    }

    /// <summary>Field number for the "heartbeat_timeout_in_ms" field.</summary>
    public const int HeartbeatTimeoutInMsFieldNumber = 5;
    private long heartbeatTimeoutInMs_;
    /// <summary>
    /// Heartbeat timeout, if a task does not record heartbeat in this time
    /// window, it will be considered disconnected.
    /// Note: This is also used as a grace period to accept any heartbeats after
    /// the agent has disconnected, to account for the lag time between the service
    /// recording the state change and the agent stopping heartbeats.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long HeartbeatTimeoutInMs {
      get { return heartbeatTimeoutInMs_; }
      set {
        heartbeatTimeoutInMs_ = value;
      }
    }

    /// <summary>Field number for the "coordinated_jobs" field.</summary>
    public const int CoordinatedJobsFieldNumber = 6;
    private static readonly pb::FieldCodec<string> _repeated_coordinatedJobs_codec
        = pb::FieldCodec.ForString(50);
    private readonly pbc::RepeatedField<string> coordinatedJobs_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// The list of jobs that partipate in the coordination service. If empty, all
    /// jobs will be included in the coordination service by default.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> CoordinatedJobs {
      get { return coordinatedJobs_; }
    }

    /// <summary>Field number for the "shutdown_barrier_timeout_in_ms" field.</summary>
    public const int ShutdownBarrierTimeoutInMsFieldNumber = 7;
    private long shutdownBarrierTimeoutInMs_;
    /// <summary>
    /// Denotes how long to wait for all coordination agents to reach the barriers
    /// (after the first shutdown request) before disconnecting together. If
    /// set to 0, no barrier is imposed upon shutdown and each worker can
    /// disconnect individually.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long ShutdownBarrierTimeoutInMs {
      get { return shutdownBarrierTimeoutInMs_; }
      set {
        shutdownBarrierTimeoutInMs_ = value;
      }
    }

    /// <summary>Field number for the "agent_destruction_without_shutdown" field.</summary>
    public const int AgentDestructionWithoutShutdownFieldNumber = 8;
    private bool agentDestructionWithoutShutdown_;
    /// <summary>
    /// If set, agents do not make an explicit Shutdown() call. Service will only
    /// find out about the disconnecte agent via stale heartbeats. Used for
    /// testing.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool AgentDestructionWithoutShutdown {
      get { return agentDestructionWithoutShutdown_; }
      set {
        agentDestructionWithoutShutdown_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CoordinationServiceConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CoordinationServiceConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ServiceType != other.ServiceType) return false;
      if (ServiceLeader != other.ServiceLeader) return false;
      if (EnableHealthCheck != other.EnableHealthCheck) return false;
      if (ClusterRegisterTimeoutInMs != other.ClusterRegisterTimeoutInMs) return false;
      if (HeartbeatTimeoutInMs != other.HeartbeatTimeoutInMs) return false;
      if(!coordinatedJobs_.Equals(other.coordinatedJobs_)) return false;
      if (ShutdownBarrierTimeoutInMs != other.ShutdownBarrierTimeoutInMs) return false;
      if (AgentDestructionWithoutShutdown != other.AgentDestructionWithoutShutdown) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ServiceType.Length != 0) hash ^= ServiceType.GetHashCode();
      if (ServiceLeader.Length != 0) hash ^= ServiceLeader.GetHashCode();
      if (EnableHealthCheck != false) hash ^= EnableHealthCheck.GetHashCode();
      if (ClusterRegisterTimeoutInMs != 0L) hash ^= ClusterRegisterTimeoutInMs.GetHashCode();
      if (HeartbeatTimeoutInMs != 0L) hash ^= HeartbeatTimeoutInMs.GetHashCode();
      hash ^= coordinatedJobs_.GetHashCode();
      if (ShutdownBarrierTimeoutInMs != 0L) hash ^= ShutdownBarrierTimeoutInMs.GetHashCode();
      if (AgentDestructionWithoutShutdown != false) hash ^= AgentDestructionWithoutShutdown.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ServiceType.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ServiceType);
      }
      if (ServiceLeader.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ServiceLeader);
      }
      if (EnableHealthCheck != false) {
        output.WriteRawTag(24);
        output.WriteBool(EnableHealthCheck);
      }
      if (ClusterRegisterTimeoutInMs != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(ClusterRegisterTimeoutInMs);
      }
      if (HeartbeatTimeoutInMs != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(HeartbeatTimeoutInMs);
      }
      coordinatedJobs_.WriteTo(output, _repeated_coordinatedJobs_codec);
      if (ShutdownBarrierTimeoutInMs != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(ShutdownBarrierTimeoutInMs);
      }
      if (AgentDestructionWithoutShutdown != false) {
        output.WriteRawTag(64);
        output.WriteBool(AgentDestructionWithoutShutdown);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ServiceType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ServiceType);
      }
      if (ServiceLeader.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ServiceLeader);
      }
      if (EnableHealthCheck != false) {
        size += 1 + 1;
      }
      if (ClusterRegisterTimeoutInMs != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ClusterRegisterTimeoutInMs);
      }
      if (HeartbeatTimeoutInMs != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(HeartbeatTimeoutInMs);
      }
      size += coordinatedJobs_.CalculateSize(_repeated_coordinatedJobs_codec);
      if (ShutdownBarrierTimeoutInMs != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ShutdownBarrierTimeoutInMs);
      }
      if (AgentDestructionWithoutShutdown != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CoordinationServiceConfig other) {
      if (other == null) {
        return;
      }
      if (other.ServiceType.Length != 0) {
        ServiceType = other.ServiceType;
      }
      if (other.ServiceLeader.Length != 0) {
        ServiceLeader = other.ServiceLeader;
      }
      if (other.EnableHealthCheck != false) {
        EnableHealthCheck = other.EnableHealthCheck;
      }
      if (other.ClusterRegisterTimeoutInMs != 0L) {
        ClusterRegisterTimeoutInMs = other.ClusterRegisterTimeoutInMs;
      }
      if (other.HeartbeatTimeoutInMs != 0L) {
        HeartbeatTimeoutInMs = other.HeartbeatTimeoutInMs;
      }
      coordinatedJobs_.Add(other.coordinatedJobs_);
      if (other.ShutdownBarrierTimeoutInMs != 0L) {
        ShutdownBarrierTimeoutInMs = other.ShutdownBarrierTimeoutInMs;
      }
      if (other.AgentDestructionWithoutShutdown != false) {
        AgentDestructionWithoutShutdown = other.AgentDestructionWithoutShutdown;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ServiceType = input.ReadString();
            break;
          }
          case 18: {
            ServiceLeader = input.ReadString();
            break;
          }
          case 24: {
            EnableHealthCheck = input.ReadBool();
            break;
          }
          case 32: {
            ClusterRegisterTimeoutInMs = input.ReadInt64();
            break;
          }
          case 40: {
            HeartbeatTimeoutInMs = input.ReadInt64();
            break;
          }
          case 50: {
            coordinatedJobs_.AddEntriesFrom(input, _repeated_coordinatedJobs_codec);
            break;
          }
          case 56: {
            ShutdownBarrierTimeoutInMs = input.ReadInt64();
            break;
          }
          case 64: {
            AgentDestructionWithoutShutdown = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
