// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: tensorboard/compat/proto/tensor_description.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tensorboard {

  /// <summary>Holder for reflection information generated from tensorboard/compat/proto/tensor_description.proto</summary>
  public static partial class TensorDescriptionReflection {

    #region Descriptor
    /// <summary>File descriptor for tensorboard/compat/proto/tensor_description.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TensorDescriptionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjF0ZW5zb3Jib2FyZC9jb21wYXQvcHJvdG8vdGVuc29yX2Rlc2NyaXB0aW9u",
            "LnByb3RvEgt0ZW5zb3Jib2FyZBo1dGVuc29yYm9hcmQvY29tcGF0L3Byb3Rv",
            "L2FsbG9jYXRpb25fZGVzY3JpcHRpb24ucHJvdG8aK3RlbnNvcmJvYXJkL2Nv",
            "bXBhdC9wcm90by90ZW5zb3Jfc2hhcGUucHJvdG8aJHRlbnNvcmJvYXJkL2Nv",
            "bXBhdC9wcm90by90eXBlcy5wcm90byKrAQoRVGVuc29yRGVzY3JpcHRpb24S",
            "JAoFZHR5cGUYASABKA4yFS50ZW5zb3Jib2FyZC5EYXRhVHlwZRIsCgVzaGFw",
            "ZRgCIAEoCzIdLnRlbnNvcmJvYXJkLlRlbnNvclNoYXBlUHJvdG8SQgoWYWxs",
            "b2NhdGlvbl9kZXNjcmlwdGlvbhgEIAEoCzIiLnRlbnNvcmJvYXJkLkFsbG9j",
            "YXRpb25EZXNjcmlwdGlvbkKTAQoYb3JnLnRlbnNvcmZsb3cuZnJhbWV3b3Jr",
            "QhdUZW5zb3JEZXNjcmlwdGlvblByb3Rvc1ABWllnaXRodWIuY29tL3RlbnNv",
            "cmZsb3cvdGVuc29yZmxvdy90ZW5zb3JmbG93L2dvL2NvcmUvZnJhbWV3b3Jr",
            "L3RlbnNvcl9kZXNjcmlwdGlvbl9nb19wcm90b/gBAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Tensorboard.AllocationDescriptionReflection.Descriptor, global::Tensorboard.TensorShapeReflection.Descriptor, global::Tensorboard.TypesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Tensorboard.TensorDescription), global::Tensorboard.TensorDescription.Parser, new[]{ "Dtype", "Shape", "AllocationDescription" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class TensorDescription : pb::IMessage<TensorDescription> {
    private static readonly pb::MessageParser<TensorDescription> _parser = new pb::MessageParser<TensorDescription>(() => new TensorDescription());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TensorDescription> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tensorboard.TensorDescriptionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TensorDescription() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TensorDescription(TensorDescription other) : this() {
      dtype_ = other.dtype_;
      shape_ = other.shape_ != null ? other.shape_.Clone() : null;
      allocationDescription_ = other.allocationDescription_ != null ? other.allocationDescription_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TensorDescription Clone() {
      return new TensorDescription(this);
    }

    /// <summary>Field number for the "dtype" field.</summary>
    public const int DtypeFieldNumber = 1;
    private global::Tensorboard.DataType dtype_ = global::Tensorboard.DataType.DtInvalid;
    /// <summary>
    /// Data type of tensor elements
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Tensorboard.DataType Dtype {
      get { return dtype_; }
      set {
        dtype_ = value;
      }
    }

    /// <summary>Field number for the "shape" field.</summary>
    public const int ShapeFieldNumber = 2;
    private global::Tensorboard.TensorShapeProto shape_;
    /// <summary>
    /// Shape of the tensor.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Tensorboard.TensorShapeProto Shape {
      get { return shape_; }
      set {
        shape_ = value;
      }
    }

    /// <summary>Field number for the "allocation_description" field.</summary>
    public const int AllocationDescriptionFieldNumber = 4;
    private global::Tensorboard.AllocationDescription allocationDescription_;
    /// <summary>
    /// Information about the size and allocator used for the data
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Tensorboard.AllocationDescription AllocationDescription {
      get { return allocationDescription_; }
      set {
        allocationDescription_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TensorDescription);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TensorDescription other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Dtype != other.Dtype) return false;
      if (!object.Equals(Shape, other.Shape)) return false;
      if (!object.Equals(AllocationDescription, other.AllocationDescription)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Dtype != global::Tensorboard.DataType.DtInvalid) hash ^= Dtype.GetHashCode();
      if (shape_ != null) hash ^= Shape.GetHashCode();
      if (allocationDescription_ != null) hash ^= AllocationDescription.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Dtype != global::Tensorboard.DataType.DtInvalid) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Dtype);
      }
      if (shape_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Shape);
      }
      if (allocationDescription_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(AllocationDescription);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Dtype != global::Tensorboard.DataType.DtInvalid) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Dtype);
      }
      if (shape_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Shape);
      }
      if (allocationDescription_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AllocationDescription);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TensorDescription other) {
      if (other == null) {
        return;
      }
      if (other.Dtype != global::Tensorboard.DataType.DtInvalid) {
        Dtype = other.Dtype;
      }
      if (other.shape_ != null) {
        if (shape_ == null) {
          Shape = new global::Tensorboard.TensorShapeProto();
        }
        Shape.MergeFrom(other.Shape);
      }
      if (other.allocationDescription_ != null) {
        if (allocationDescription_ == null) {
          AllocationDescription = new global::Tensorboard.AllocationDescription();
        }
        AllocationDescription.MergeFrom(other.AllocationDescription);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Dtype = (global::Tensorboard.DataType) input.ReadEnum();
            break;
          }
          case 18: {
            if (shape_ == null) {
              Shape = new global::Tensorboard.TensorShapeProto();
            }
            input.ReadMessage(Shape);
            break;
          }
          case 34: {
            if (allocationDescription_ == null) {
              AllocationDescription = new global::Tensorboard.AllocationDescription();
            }
            input.ReadMessage(AllocationDescription);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
